#!/bin/bash

# This script copies the information from all Girdsum files in a file tree
# and stores it in one big file, updating all the filenames to include
# their relative paths.
#
#     gird-collect Photos

# TODO: If a Girdtree file already exists in the named directory,
# we should verify that file rather than creating a new one.

find "${1:-.}" -type f -name Girdsums -print0 |
  xargs -0 -n1 -I{} sh -c 'sed s/\\./"$(
    echo {} | sed "s/\\\\/\\\\\\\\/g; s|/|\\\\/|g; s/&/\\\\&/g; s|\\\\/Girdsums$||"
    )"/ "{}"' | sort -k2 > Girdtree
