#!/bin/bash

# Run this script to generate hashes for every file in a directory tree:
#    gird ~/Photos
# Each directory will now have a file named Girdsums in it.
#
# Run gird again to verify the hashes and ensure the directory contents haven't changed.
# Gird will not modify an existing Girdsums file unless forced.
#
# We compute the checksums for the files in this directory
#   If there's an existing checksums file
#     Then compare it to the new checksums
#       If the directory contents are different, PRINT A PANIC
#       If any file digests have changed, PRINT A PANIC

gird_directory () {
  local path="$1"
  if [ -e Girdsums.inprogress ]; then
    echo "$path: Girdsums.inprogress already exists. Is another Gird running? Exiting."
    kill $ogpid; exit
  fi

  find . -type f -maxdepth 1 \
    -not -name Girdsums \
    -not -name Girdsums.inprogress \
    -not -name .DS_Store \
    -print0 | sort -z | xargs -0 shasum -a 1 > Girdsums.inprogress

    if [ -e Girdsums ]; then
      local differences="$(diff -u Girdsums Girdsums.inprogress)"
      if [ -z "$differences" ]; then
        rm Girdsums.inprogress
      else
        echo "$path: gird verification failed"
        echo "$differences"
        kill $ogpid; exit
      fi
    else
      mv Girdsums.inprogress Girdsums
    fi
}
export -f gird_directory

export ogpid=$$ # kill this pid to abort
find "${1:-.}" -type d -print0 |
  xargs -0 -n1 -I{} sh -c 'echo processing "{}"; cd "{}"; gird_directory "{}"'
